databases:
  - name: rails-watch-list
    databaseName: rails-watch-list
    user: rails-watch-list

services:
  - type: web
    name: rails-watch-list
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
